" Enabling filetype support provides filetype-specific indenting,
" syntax highlighting, omni-completion and other useful settings.
filetype plugin indent on
let g:solarized_termcolors=256
set t_Co=256
syntax enable
set background=dark
colorscheme solarized  " solarized.vim must exist in ~/.vim/colors

" `matchit.vim` is built-in so let's enable it!
" Hit `%` on `if` to jump to `else`.
runtime macros/matchit.vim

" various settings
set nocompatible       " more advanced features
set backspace=2        " better backspace behaviour
set showcmd            " Show (partial) command in status line.
set showmatch          " Show matching brackets.
set ignorecase         " Do case insensitive matching
set incsearch          " Incremental search
set hlsearch           " highlight searches
set autowrite          " Automatically save before commands like :next & :make
set autoindent                 " Minimal automatic indenting for any filetype.
set pastetoggle=<F3>           " Toggles pastemode
set hidden                     " Possibility to have more than one unsaved buffers.
set ruler                      " Shows the current line number at the bottom-right of the screen.
set wildmenu                   " Great command-line completion, use `<Tab>` to move around and `<CR>` to validate.
set history=1000               " More than the default 8 commands
set encoding=utf-8


" netrw setting
let g:netrw_banner = 0
let g:netrw_liststyle = 3
let g:netrw_browse_split = 4
let g:netrw_altv = 1
let g:netrw_winsize = 25
"augroup ProjectDrawer
"        autocmd!
"        autocmd VimEnter * :Vexplore
"augroup END"






